### ISSUE TITLE
ELException /WEB-INF/views/resource.jsp under Wildfly

### ISSUE THREAD

**Issue by AlexanderWillner** [dvcama/LodView#11]
Description: ELException when opening HTML rendering
Version: a4d390a3d84a3107c720b856a862825b2b5f1f54  on Wildfly 9.0.1

Steps that will reproduce the problem?
1. Install a4d390a3d84a3107c720b856a862825b2b5f1f54 on WildFly 9.0.1
2. Open the HTML rendering of a resource

What is the expected result?
The web site

What happens instead?
```Caused by: javax.el.ELException: Error Parsing: ${results.getTitle().replaceAll("\\n"," ").replaceAll("\'","&acute;")}``` in ```/WEB-INF/views/resource.jsp```

Possible workaround:
Edit line 181 and remove the second ```replaceAll```

Any additional information:

**Comment by dvcama** [comment]
the "replaceAll" is here src/main/webapp/WEB-INF/views/inc/scripts.jsp  at line 181, but I don't understand why WildFly sees an error and tomcat does not,  it seems correct... 

Anyway, I double escaped it 
https://github.com/dvcama/LodView/commit/ae55596ce1830d6d29c7e83b8f96be687648810a
