### ISSUE TITLE
conf:httpRedirectSuffix ".html" forwards to localhost:8080

### ISSUE THREAD

**Issue by AlexanderWillner** [dvcama/LodView#12]
Version: a4d390a3d84a3107c720b856a862825b2b5f1f54

Steps that will reproduce the problem?
1. curl -v http://example.org/id/about

What is the expected result?
```
HTTP/1.1 303 See Other
Location: http://example.org/id/about.html
```

What happens instead?
```
HTTP/1.1 303 See Other
Location: http://localhost:8080/about.html
```

Possible workaround:
Disable conf:httpRedirectSuffix and all works fine.

**Comment by dvcama** [comment]
I don't see the point, please don't use that workaround... probably the default conf file is not right, I'll check it out

in the meanwhile I have populated this page https://github.com/dvcama/LodView/wiki/how-to:-redirection-and-content-negotiation providing some examples

**Comment by dvcama** [comment]
I fixed the default conf.ttl

https://github.com/dvcama/LodView/commit/2c8d02bf38d8b13bcd6fdbca2bec5cdee8be3fa3
