### ISSUE TITLE
Russian uri doesn't open.

### ISSUE THREAD

**Issue by DiegoMoussallem** [dvcama/LodView#17]
Hi, 

Congratulations for the tool, it is amazing and i really liked. I'm using in my data set about idioms however when i wish to open a uri in Russian language, the lodview doesn't recognized the letters. Could you help me? Follows an example  with error: 

Russian : http://lid.aksw.org/tr/когда_рак_на_горе_свистнет_trans_rus_en

Look as it works for other languages which I've used: 

English: http://lid.aksw.org/en/when_pigs_fly_sense

German: http://lid.aksw.org/lodview/de/zwei_fliegen_mit_einer_klappe_schlagen

Portuguese: http://lid.aksw.org/lodview/pt/matar_dois_coelhos_com_uma_cajadada_so

Italian: http://lid.aksw.org/lodview/it/alle_calende_greche

**Comment by dvcama** [comment]
hello,

IRIs are always a problem... there are a lot of components (web server, proxies, endpoint, etc) involved in the IRI decoding/encoding process

try to change this parameter in conf.ttl
	conf:forceIriEncoding "auto"; ## or "decode" or "encode"

and see what fits better according to your environment

**Comment by DiegoMoussallem** [comment]
hmm. I've changed it and no one worked only "auto". =/

**Comment by dvcama** [comment]
are you using the git-cloned version of lodview or a particular release?

**Comment by DiegoMoussallem** [comment]
git-cloned.

**Comment by dvcama** [comment]
mmm, I need more info about the environment, write me at info@lodlive.it if you want more help

**Comment by dvcama** [comment]
did you have done this? 
https://github.com/dvcama/LodView/wiki/how-to:-install-and-configure-(fast-method)#very-important

**Comment by DiegoMoussallem** [comment]
Yes I did.I think that this problem is something related to russian alphabet when the browser read the dump files.
