### ISSUE TITLE
LodView vs lodview.it

### ISSUE THREAD

**Issue by brodecva** [dvcama/LodView#18]
Hi,
first let me thank you for this great tool!

I'd like to ask you whether you ever plan to open-source the features that the lodview.it service has and the version on Github does not, mainly "the browsing of any resource published using a SPARQL endpoint or published according to the rules of the web of data (aka content negotiation and RDF)".

_The reasoning behind my question is that in our school project we needed a tool to display remote resource in a pleasing way (at least in the early stages, before we will work with our local copies our our published resource) and also add some buttons that would link back to our application from the displayed concept (e.g. to accept the displayed result as the one chosen by the _user)._

_Based on the demo at lodview.it we decided to go with LodView. Only to realize later that this functionality is seemingly not available or even has been stripped away. (We should have read the README.md more carefully.) Although we eventually managed to crudely  adapt the LodView to our needs in our fork, its reliance on global static configuration in determining the resource to display is less than ideal._

**Comment by dvcama** [comment]
Hi, 
I don't want to share it on github just because I do not have any time to implement my (already poor) documentation... If you are going to use it for "school reason" I can send you the source code, just contact me on info@lodlive.it

**Comment by KonradHoeffner** [comment]
Environment variable support is implemented in https://github.com/LodLive/LodView/pull/47 however that is not merged yet.

**Comment by JJ-Author** [comment]
> Environment variable support is implemented in [#47](https://github.com/LodLive/LodView/pull/47) and is now merged into the master branch so you can use it there.

thanks for your work on this @KonradHoeffner.
I’m not quite sure I understand the connection to environment variables here.

The goal of  "browsing of any resource published using a SPARQL endpoint" dynamically/ at runtime (so without static configuration) using one lodview instance (similiar as provided by lodview.it) is being able to to sth. like this:

https://$my_lodview_host/lodview/?IRI=$resource_iri&sparql=$sparql_endpoint_of_resource&prefix=$namespace

Could you clarify how your PR would help to achieve this, please?

**Comment by KonradHoeffner** [comment]
@JJ-Author as this was over 3 years ago and I'm not using LodView anymore (I developed my own RDF Browser in Rust calling RickView using the design of LodView) I'm also not sure, maybe I misunderstood it at the time as it seems not exactly the use case of a dynamic instance but instead easier configuration of a single instance for a fixed knowledge base.
