### ISSUE TITLE
Change engine to RDF4J

### ISSUE THREAD

**Issue by jgrzebyta** [dvcama/LodView#20]
Nice work. Congratulations. I am impressed of data linkage. 

Would it be possible to rewrite the engine into [RDF4J-base](https://github.com/eclipse/rdf4j). I saw the code and it seems it is not too complex for me. What do you think about that?

**Comment by dvcama** [comment]
thank you,

which advantages you think we are going to have from that?

**Comment by jgrzebyta** [comment]
I thought about having an option for closer integration with the triple store engine to avoid http infrastructure in-between (web servlets, etc). Also RDF4J supports multi-threading communication so there is better performance. 

However someone advised a better solution with different approach so I close that issue.
