### ISSUE TITLE
LodView on SSL

### ISSUE THREAD

**Issue by roland-c** [dvcama/LodView#21]
Hi,
I run an instance of LodView on an SSL secured website. The browser warns about mixed content when loading a resource page. Warnings are about fetching content from OpenStreetMap such as http://b.tile.osm.org/8/131/83.png, which connection is insecure. 
Is there a solution for this? I tried to change http://b.tile.osm.org/8/131/83.png into **https**://b.tile.osm.org/8/131/83.png but that didn't work.
Thanks,
Roland

**Comment by dvcama** [comment]
hello,
I made this change https://github.com/dvcama/LodView/commit/5e02268213a7da75f81a9c4edfc701b47440e976#diff-a8f8ccf8aead2f6e994cef7efbc01a51

I didn't try it, please let me know if it works
