### ISSUE TITLE
Colors by prefix?

### ISSUE THREAD

**Issue by KonradHoeffner** [dvcama/LodView#23]
conf.ttl states that there is an option to choose colors randomly or to assign color by class. Is it also possible to assign color by prefix?

For example, resources under `http://dbpedia.org/resource/` should have a different color then resources under `http://dbpedia.org/ontology/`.

If it does not exist yet I propose it as a new feature.

This could also be implemented by allowing regular expressions for "colors by class", e.g.:

`<http://dbpedia.org/ontology/.*>            conf:hasColorPair       "#c3a116-#ac8c13". `

**Comment by dvcama** [comment]
hi,

this use case never really happened to me ... but I can see the point 

are you going to publish data using LodView? I mean, do you need this feature for some new publication?

**Comment by KonradHoeffner** [comment]
I am going to publish the [SNIK ontology](www.snik.eu), which models textbook knowledge about Hospital Information Management. Each textbook has a different prefix and we refer to them by their color. E.g. there is the "blue book" and the "orange book".

**Comment by KonradHoeffner** [comment]
I try to implement it myself I don't understand the configuration code. In `ConfigurationBean.populateBean()`, the color list is parsed but I don't find the code that processes `conf:byClass`.

**Comment by KonradHoeffner** [comment]
I try to implement this myself now by changing ConfigurationBean.java. If you are interested, I can send you a pull request when it is finished.

**Comment by KonradHoeffner** [comment]
Made a pull request with the prefix color feature.
