### ISSUE TITLE
Inverse relations missing

### ISSUE THREAD

**Issue by KonradHoeffner** [dvcama/LodView#24]
I cloned LodView from the master branch (commit 5e02268213a7da75f81a9c4edfc701b47440e976) and it does not load any inverse relations even though the text message "loading inverse relations" is shown in the bottom. I am debugging it in Eclipse Neon.1a using the run-jetty-run plugin.

I have the following breakpoints and not one of them stops:

`ResourceBuilder.buildInverseResource()` (both of them)
`LinkedResource.resourceInverses()` (both of them)

**Comment by dvcama** [comment]
I just cloned the project again and it works properly (try opening http://localhost:8080/lodview/Rome) 
did you change anything in the configuration file? 

these three queries are involved in inverse relations generation
`conf:defaultInversesQueries "select distinct ?p {?p <${PROPERTY}> <${IRI}>.}  OFFSET ${STARTFROM} LIMIT 10"; `
`conf:defaultInversesCountQueries "select (count(distinct ?s) AS ?o) ?p {?s ?p <${IRI}>. FILTER(!isBlank(?s))} GROUP BY ?p LIMIT 100";`
`conf:defaultInversesTest "ASK {?s ?p <${IRI}>}";`

are they working in your environment? 
any javascript errors?

let me know

**Comment by KonradHoeffner** [comment]
You are right, the error was in `conf.ttl`, which I adapted to our project.
I fixed the inverse relations by changing
`conf:publicUrlPrefix <http://www.mydomain.eu/ontology/>;`

back to 

`conf:publicUrlPrefix <auto>;`

I see that it was incorrect though because I was testing it locally but I didn't expect it to only break the inverse relations.
