### ISSUE TITLE
Show properties of regular linked nodes in html view.

### ISSUE THREAD

**Issue by renevoorburg** [dvcama/LodView#28]
In config.ttl one can specify what SPARQL query to perform for a requested URI. However, when one includes none blank nodes these regular nodes will not be displayed in the regular html view.

**Comment by dvcama** [comment]
please give me info if this still apply

**Comment by renevoorburg** [comment]
Hello Diego,

It still does.

An example:

We have configured the combination of Apache webserver and Lodview to redirect requests for uris like domain/id/thing to domain/doc/thing.

On the domain/doc/thing page Lodview shows now, as it should, the properties and properties of nested blank nodes of domain/id/thing . However, we also want it to show the properties for domain/doc/thing . We can configure lodview with regards to what query to do for adding nested blank nodes but we can get it to display the properies of the /doc/thing.


An example: What we want to say in RDF is

<this thing> <is the topic of> <this page that describes it> .

Or for example:

<http://data.bibliotheken.nl/id/nbt/p357539168 <http://data.bibliotheken.nl/id/nbt/p357539168>> foaf:isPrimaryTopicOf <http://data.bibliotheken.nl/doc/nbt/p357539168 <http://data.bibliotheken.nl/doc/nbt/p357539168>> .

However, as I explained, since we  can get http://data.bibliotheken.nl/doc/nbt/p357539168 <http://data.bibliotheken.nl/doc/nbt/p357539168> only to present the propertis of http://data.bibliotheken.nl/id/nbt/p357539168 <http://data.bibliotheken.nl/id/nbt/p357539168> and not of /doc/ itself we now had to follow this kind of nasty approach:

<http://data.bibliotheken.nl/id/nbt/p357539168 <http://data.bibliotheken.nl/id/nbt/p357539168>> 
	{all sort of properties of /id/.. } ,
	foaf:isPrimaryTopicOf  [
		a foaf:Document ,
		owl:sameAs <http://data.bibliotheken.nl/doc/nbt/p357539168 <http://data.bibliotheken.nl/doc/nbt/p357539168>>  ,
		foaf:primaryTopic <http://data.bibliotheken.nl/id/nbt/p357539168 <http://data.bibliotheken.nl/id/nbt/p357539168>> , 
		{other properties of the describing document}
	] .

(You may follow the URIs to see it in online) 
That solves the problem more or less but is very confusing to many users. Basically we would like Lodview to show on a single page:

<http://data.bibliotheken.nl/id/nbt/p357539168 <http://data.bibliotheken.nl/id/nbt/p357539168>> 
	{all sort of properties of /id/.. } ,
	foaf:isPrimaryTopicOf  <http://data.bibliotheken.nl/doc/nbt/p357539168 <http://data.bibliotheken.nl/doc/nbt/p357539168>>  .

 <http://data.bibliotheken.nl/doc/nbt/p357539168 <http://data.bibliotheken.nl/doc/nbt/p357539168>> 
		a foaf:Document ,
		foaf:primaryTopic <http://data.bibliotheken.nl/id/nbt/p357539168 <http://data.bibliotheken.nl/id/nbt/p357539168>> , 
		{other properties of the describing document} .


Besides that we are quite happy with Lodview  but this is for us a reason now to look around for other options. Any news on this issue would be greatly appreciated!

Cheers,
René Voorburg
