### ISSUE TITLE
Map representation widget

### ISSUE THREAD

**Issue by barrynl** [dvcama/LodView#30]
TODO: manage shape representation.

We are using the wkt:asWKT property to describe the polygon of our spatial objects. It would be great if these polygons would be shown by LodView instead of only GPS coordinate spatial objects.

I would (technically) be able to extend the widget myself and contribute it to this project, but I'm not sure yet if I can find the time.

**Comment by dvcama** [comment]
I would love to have your help... sadly I don't have much time myself (one year to answer to this should really prove this point!)
