### ISSUE TITLE
Content-Negotiation is not working

### ISSUE THREAD

**Issue by l00mi** [dvcama/LodView#33]
Without looking into the code myself, we get the following error on http://lodview.it/lodview/?IRI=https%3A%2F%2Fld.geo.admin.ch%2Fboundaries%2Fmunicipality%2F351&sparql=%3C%3E&prefix=https%3A%2F%2Fld.geo.admin.ch%2Fboundaries%2Fmunicipality%2F351

>  Oops! something went wrong 
> 
> sorry but content negotiation is not supported by the IRI 
> <https:​/​/​ld.​geo.​admin.​ch/​boundaries/​municipality/​351>

I am able to ask for e.g. text/turtle success fully on the resource. What are the requirements on the resource to be loaded regarding content-neg?

**Comment by dvcama** [comment]
lodview uses Jena to connect and download the resource
here is the exact point where it happens
https://github.com/dvcama/LodView/blob/db430880b48c1f0ad659e16aeafb1fbc55f4c40b/src/main/java/org/dvcama/lodview/controllers/ResourceController.java#L382

```
com.hp.hpl.jena.rdf.model.Model m = ModelFactory.createDefaultModel();
m.read(IRI);
```
if this throws an exception lodview will return a 500 error
