### ISSUE TITLE
IE9 compatibility issue 

### ISSUE THREAD

**Issue by miyamotodan** [dvcama/LodView#9]
I had some problem in resource visualization con IE9 (Masonry js lib error).

![masonry](https://cloud.githubusercontent.com/assets/5948419/7160279/4da92b36-e388-11e4-90db-bd069a75c8a1.JPG)

Some text in the page was overlapped.

![overlap](https://cloud.githubusercontent.com/assets/5948419/7160283/5143c0b2-e388-11e4-9622-7b0ab9a8bfd1.JPG)

I think this is due to a compatibility issue that can be fixed adding a meta-tag just after the <head> tag

<meta http-equiv="x-ua-compatible" content="IE=Edge"/>

**Comment by dvcama** [comment]
to fix it, as you privately suggested, I added 
<meta http-equiv="x-ua-compatible" content="IE=Edge"/>

https://github.com/dvcama/LodView/blob/master/src/main/webapp/WEB-INF/views/inc/header.jsp#L8
